import io
from huggingface_hub import InferenceClient

# Load HF API key from environment
HF_API_KEY = st.secrets["HF_API_KEY"]
client = InferenceClient(api_key=HF_API_KEY)

# ------------------------------------------------------
# Text → Speech (MP3 bytes output)
# ------------------------------------------------------
def text_to_speech(text: str):
    """
    Returns MP3 audio bytes generated by HuggingFace TTS model.
    Streamlit can play this audio bytes directly.
    """

    if not text or not text.strip():
        return None

    try:
        # TTS model: Fast & high quality
        model = "facebook/fastspeech2-en-ljspeech"

        response = client.text_to_speech(
            model=model,
            text=text,
            voice="female",
        )

        # Convert streamed output to bytes
        audio_bytes = io.BytesIO(response.read())
        return audio_bytes.getvalue()

    except Exception as e:
        print("TTS ERROR:", e)
        return None
